### ISSUE TITLE
About the capability of RSS feed generation.

### ISSUE THREAD

**Issue by AboutRSS** [sawyerf/Youtube_subscription_manager#7]
There is a "HTML & RSS" category but no RSS related information in main content below. So, will it generate a RSS feed for target channel? Found nothing on exmaple page.

**Comment by sawyerf** [comment]
Hello,
Youtube-sm use the [rss page](http://www.youtube.com/feeds/videos.xml?channel_id=ID) to retrieve the last videos released and generate a html/json/list file. So that does not generate a RSS feed. If you want a RSS feed for youtube you can use the official RSS feed (http://www.youtube.com/feeds/videos.xml?channel_id=CHANNEL_ID). :)

**Comment by sawyerf** [comment]
The [example page](https://sawyerf.gitlab.io/youtube_sm/example.html) you mention is a output of the program.
